### ISSUE TITLE
Pebble 2

### ISSUE THREAD

**Issue by Flavien06** [Sorunome/pebble-mpd-client#2]
Hi
Do you plan to support the Pebble 2?
Thank

**Comment by Sorunome** [comment]
I have no access to anybody who has a pebble 2 to test, are you willing to do that?

**Comment by Flavien06** [comment]
Yes, I can test

**Comment by Sorunome** [comment]
Ok, that's cool. Currently I'm very busy because of university, I'll get back to you once I have time.

In case you know programming stuff etc. it should in theory work if you just fork this repo and add the pebble2 as supported watch and just compile&upload

**Comment by Sorunome** [comment]
So, I think I added support now, you can find the pbw file here: https://files.sorunome.de/pebble-mpd-client.pbw

If you are reporting that it is working then i'll update the build on the normal pebble app store!

Be sure to check out the readme (front page of this wiki) for full installation instructions, as unfortunately it might take a bit more...

**Comment by Flavien06** [comment]
I have error with the python script
`pi@raspberrypi:~/pebble-mpd-server $ sudo python3 pebble_mpd_proxy.py`
`Traceback (most recent call last):`
`File "pebble_mpd_proxy.py", line 8, in <module>`
`from mpd import MPDClient`
`ImportError: No module named 'mpd'`

an idea ?

**Comment by Sorunome** [comment]
eeeer, yeah `sudo pip3 install python-mpd2` forgot to add that to the instructions, lol

EDIT: Also, i wouldn't recommend running the pebble_mpd_proxy.py as root

**Comment by Flavien06** [comment]
Yes it works. I need to install  `sudo apt-get install python3-pip`
Everything works except the volume

Log from serveur [http://txt.do/d5ptb](http://txt.do/d5ptb)

**Comment by Sorunome** [comment]
Which MPD server version are you running?

EDIT: nevermind the logs say it, i'm investigating

**Comment by Flavien06** [comment]
Version: `Music Player Daemon 0.19.1`
Video from the test (if necessary) [https://www.youtube.com/watch?v=SzR8ahEvHZs](https://www.youtube.com/watch?v=SzR8ahEvHZs)
Other bug at 0:15 and volume at 0:38

**Comment by Sorunome** [comment]
The bug at 0:15 might actually not be a bug but because you reached the end of your playlist and didn't set MPD to loop - is that correct?

The thing is, the mpd client actually just obays the server if it is playing/pausing/stopping or something, it never just guesses the state.

**Comment by Sorunome** [comment]
Also, does changing volume work with other clients? (so are you sure it isn't a miss-configured MPD server?)

**Comment by Sorunome** [comment]
I think I might have fixed the issue, only `pebble_mpd_proxy.py` changed.

**Comment by Flavien06** [comment]
When I use vol + on pebble, the MDP vol set to 5
`{'action': 'commands', 'commands': ['setvol 5']}`

And vol - set to 0

**Comment by Sorunome** [comment]
When increasing pebble-mpd increases by 5, when decreasing it decreases by 5, that is correct. Or do you mean only 0 and 5 are possible states?

**Comment by Flavien06** [comment]
0 and 5 only possible states.

**Comment by Sorunome** [comment]
I think I fixed it, you will need to update the python server and the pbw file for the pebble, you can find the pbw file again here: https://files.sorunome.de/pebble-mpd-client.pbw

Thanks for taking your time to test this! :D

**Comment by Flavien06** [comment]
I have this error :

> `{'commands': ['setvol NaN'], 'action': 'commands'}
> Traceback (most recent call last):
>   File "pebble_mpd_proxy.py", line 288, in on_message
>     self.mpd.setvol(int(p[1]))
> ValueError: invalid literal for int() with base 10: 'nan'
> 
> {'commands': ['setvol NaN'], 'action': 'commands'}
> Traceback (most recent call last):
>   File "pebble_mpd_proxy.py", line 274, in on_message
>     self.mpd.command_list_ok_begin()
>   File "/usr/local/lib/python3.4/dist-packages/mpd.py", line 577, in command_list_ok_begin
>     raise CommandListError("Already in command list")
> mpd.CommandListError: Already in command list
> 
> {'commands': ['pause 1'], 'action': 'commands'}
> Traceback (most recent call last):
>   File "pebble_mpd_proxy.py", line 274, in on_message
>     self.mpd.command_list_ok_begin()
>   File "/usr/local/lib/python3.4/dist-packages/mpd.py", line 577, in command_list_ok_begin
>     raise CommandListError("Already in command list")
> mpd.CommandListError: Already in command list`

**Comment by Sorunome** [comment]
Did you really update your pbw-file? If you did so, mind getting me debug log of that? For that, turn on debugging settings in the pebble app and then do `pebble logs --phone <ip>`

BEWARE: IT MIGHT CONTAIN YOUR PASSWORD TO YOUR MPD SERVER

**Comment by Flavien06** [comment]
Yes I have remove old MPD Client from Pebble App and install new pbw

for use `pebble logs --phone <ip>` I can use in cloudpebble?

**Comment by Sorunome** [comment]
Yeah, you should be able to view the debug log with cloudpebble, too

**Comment by Flavien06** [comment]
How conect to phone with cloudpebble?

**Comment by Sorunome** [comment]
I don't know, sorry, I always connect directly

**Comment by Sorunome** [comment]
Should be fixed in https://github.com/Sorunome/pebble-mpd-client/releases/tag/1.1.0

If it isn't, please open a new issue (We kinda went off-topic from the original issue with 2.0 support, which has been added with 1.1.0, too)
